// Generated by CoffeeScript 1.10.0
'use strict';
var Todo, express, parser, router;

express = require('express');

parser = require('body-parser');

Todo = require('../models/todo');

router = express.Router();

router.get('/todos', function(req, res) {
  return Todo.find({}, function(error, todos) {
    if (error) {
      return res.status(500).json({
        message: error.message
      });
    }
    return res.json({
      todos: todos
    });
  });
});

router.post('/todos', function(req, res) {
  var todo;
  todo = req.body;
  return Todo.create(todo, function(error, todo) {
    if (error) {
      return res.status(500).json({
        error: error.message
      });
    }
    return res.json({
      'todo': todo,
      message: 'Todo Created'
    });
  });
});

router.put('/todos/:id', function(req, res) {
  var id, todo;
  id = req.params.id;
  todo = req.body;
  if (todo && todo._id !== id) {
    res.status(500).json({
      error: "Ids don't match!"
    });
  }
  return Todo.findByIdAndUpdate(id, todo, {
    "new": true
  }, function(error, todo) {
    if (error) {
      return res.status(500).json({
        error: error.message
      });
    }
    return res.json({
      'todo': todo,
      message: 'Todo Updated'
    });
  });
});

router["delete"]('/todos/:id', function(req, res) {
  var id;
  id = req.params.id;
  return Todo.findByIdAndRemove(id, function(error) {
    if (error) {
      return res.status(500).json({
        error: error.message
      });
    }
  });
});

module.exports = router;
