// Generated by CoffeeScript 1.10.0
'use strict';
var model, mongoose, todoSchema;

mongoose = require('mongoose');

todoSchema = new mongoose.Schema({
  name: String,
  completed: Boolean
});

model = mongoose.model('Todo', todoSchema);

module.exports = model;
