// Generated by CoffeeScript 1.10.0
'use strict';
var mongoose;

mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/mean-todo', function(error) {
  if (error) {
    return console.log('Failed to connect mongodb!');
  } else {
    return console.log('successfully connected to mongodb');
  }
});
