// Generated by CoffeeScript 1.10.0
'user strict';
var Todo, todos;

Todo = require('./models/todo.js');

todos = ['Feed the dog', 'Walk the kids', 'Water the trees'];

todos.forEach(function(todo, index) {
  return Todo.find({
    name: todo
  }, function(error, todos) {
    if (!error && !todos.length) {
      return Todo.create({
        complete: false,
        name: todo
      });
    }
  });
});
